import thinky from '../thinky';

let type = thinky.type;

let Config = thinky.createModel('Config', {
    id              : type.string().optional(), // Optional => not specified in bodies but generated by RethinkDB
    doubleValidation: Boolean,
    offlineSupport  : Boolean,
    alcohol         : Boolean,
    createdAt       : type.date().default(new Date()),
    editedAt        : Date,
    isRemoved       : type.boolean().default(false)
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

Config.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

Config.associate = () => {};

export default Config;
