import thinky from '../thinky';

let type = thinky.type;

let MeanOfLogin = thinky.createModel('MeanOfLogin', {
    id       : type.string().optional(), // Optional => not specified in bodies but generated by RethinkDB
    type     : type.string().enum('etuId', 'etuMail'),
    data     : type.any(), // String or Number
    createdAt: type.date().default(new Date()),
    editedAt : Date,
    isRemoved: type.boolean().default(false),
    // Force Thinky to show thoses additional fields that would be cut by enforce_extra
    userId   : type.string().optional()
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

MeanOfLogin.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

MeanOfLogin.ensureIndex('type');
MeanOfLogin.ensureIndex('createdAt');
MeanOfLogin.ensureIndex('editedAt');

MeanOfLogin.associate = models => {
    models.MeanOfLogin.belongsTo(models.User, 'user', 'userId', 'id');
};

export default MeanOfLogin;
