import thinky from '../thinky';

let type = thinky.type;

let MeanOfPayment = thinky.createModel('MeanOfPayment', {
    id       : type.string().optional(), // Optional => not specified in bodies but generated by RethinkDB
    slug     : type.string(),
    name     : type.string(),
    createdAt: type.date().default(new Date()),
    editedAt : Date,
    isRemoved: type.boolean().default(false)
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

MeanOfPayment.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

MeanOfPayment.ensureIndex('createdAt');
MeanOfPayment.ensureIndex('editedAt');

MeanOfPayment.associate = () => {};

export default MeanOfPayment;
