import thinky from '../thinky';

let type = thinky.type;

let Right = thinky.createModel('Right', {
    id       : type.string().optional(), // Optional => not specified in bodies but generated by RethinkDB
    name     : String,
    isAdmin  : type.boolean().default(false),
    createdAt: type.date().default(new Date()),
    editedAt : Date,
    isRemoved: type.boolean().default(false)
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

Right.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

Right.ensureIndex('name');
Right.ensureIndex('isAdmin');
Right.ensureIndex('createdAt');
Right.ensureIndex('editedAt');

Right.associate = models => {
    models.Right.hasAndBelongsToMany(models.User, 'users', 'id', 'id');
};

export default Right;
